name: game_note
description: A new Flutter project.
publish_to: 'none'
version: 0.8.0+21

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  sqflite: ^2.0.2+1
  path: ^1.8.0
  get_it: ^7.2.0
  flutter_fortune_wheel: ^1.2.0
  provider: ^6.0.3
  equatable: ^2.0.3
  bloc: ^8.1.0
  flutter_bloc: ^8.0.1
  # Functional programming thingies
  dartz: ^0.10.1

  file_picker: ^8.1.2

  share_plus: ^10.0.2
  shared_preferences: ^2.0.15
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.3

  fl_chart: ^0.68.0
  collection: ^1.18.0
  cloud_firestore: ^4.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^4.0.0
  
flutter:

  uses-material-design: true
  
  assets:
    - assets/images/

