name: game_note
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+22

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  sqflite: ^2.0.2+1
  path: ^1.8.0
  get_it: ^7.2.0
  flutter_fortune_wheel: ^1.2.0
  provider: ^6.0.3
  equatable: ^2.0.3
  bloc: ^8.1.0
  flutter_bloc: ^8.0.1
  # Functional programming thingies
  dartz: ^0.10.1

  file_picker: ^8.0.7
  share_plus: ^10.0.0

  shared_preferences: ^2.0.15

  fl_chart: ^0.69.0
  collection: ^1.18.0
  google_sign_in: ^6.2.1
  package_info_plus: ^8.0.2

  cached_network_image: ^3.4.0

  # Firebase
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  firebase_storage: ^12.2.0
  cloud_firestore: ^5.4.0

  # URL Launcher
  url_launcher: ^6.3.0

  # Image picker
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^4.0.0
  
flutter:

  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/province.json

