name: Android Release

on:
  push:
    branches: ["main"]

  # allow manual trigger on actions tab
  workflow_dispatch:

jobs:
  # build qua reusable workflow để đảm bảo identical với build trên develop
  build:
    uses: ./.github/workflows/_android-build.yml
    secrets: inherit

  # deploy to play store
  deploy:
    name: Deploy Android Build
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Get Android Build from artifacts
        uses: actions/download-artifact@v4
        with:
          name: android-release
      - name: Release Build to internal track
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAYSTORE_ACCOUNT_KEY }}
          packageName: com.november.game_note
          releaseFiles: app-release.aab
          # build open testing
          # track: beta
          # build production
          track: production
          status: completed
